string *adverbs;
string *e_array;
mapping e_map;

reset(arg) {
string poss;
  if(arg) return;

poss=this_player()->query_possessive();

adverbs = ({ 
"absurdly","abhorrently","abidingly","ably","abruptly","absently","absolutely",
"abruptly","absently","absolutely","absurdly","academically","accidentally",
"adamantly","addictively","adeptly","affectionally", "admiringly","aggressively",
"aghastly","amazedly","angelically", "angrily","annoyedly","appreciatively",
"appealingly","approvingly", "arrogantly", "ardently","arousedly",
"assumingly","astonishedly","attentively","attractively","audibly","awfully",
"awkwardly",

"badly", "baldly","barbarically", "bashfully", "beautifully",
"benevolently","biblically","bitterly","blankly","blasphemously","blatantly",
"bluntly", "bluishly", "boastfully", "boldly","boredly", "boringly","briefly",
"brilliantly","brotherly","brutally", 

"cadavrously","calculatingly","calmly", "casually", "charismatically",
"cheesily", "cheerfully", "childishly","chivalrously", "clearly", "cleverly", 
"closely", "coldly", "comically", "comfortingly", "confusingly", "contently", 
"contentedly", "conspiratorially", "cruelly", "cutely", 

"dangerously","daringly","darkly", "decently", "deeply", "defiantly",
"deliciously","delicately","determinedly", "demonically", "diabolically", 
"dignifiedly", "dirtily", "disgustingly", "disgustedly", "disappointedly", 
"disapprovingly", "dizzily", "drily", "drunkenly","dryly","dumbly",

"eagerly","easily","eerily", "elegantly", "endlessly", "enigmatically", "entertainingly",  
"elegantly","endlessly", "enthusiastically", "enthousiastically", "erotically", 
"erratically", "evilly", 

"fabulously", "fearfully", "fearlessly", 
"fiendishly", "fiercefully", "firmly", "flirtingly","flegmatically","fluently", 
"fondly", "foolishly","forcefully","frankly", "frantically", "frenetically", 
"friendly", "frustratedly","fully", "fretfully", "funnily", 

"generously","gently", "girlishly", "gleefully", "gloomily", "goofily",
"good-heartedly","gracefully", "graciously", "gratefully", "greedily",

"happily", "hatefully", "heartily", "heartlessly", "heavily",
"heinously", "hellishly", "helpfully", "helplessly", "hilariously", "hopefully", 
"hopelessly", "hornily", "horribly", "humbly", "hungrily", "hysterically", 

"idly", "idiotically", "impatiently", "impotently", "inanely", 
"intensely","inconsolably", "indecently", "insanely", "intensely", 

"jovially","joyfully","joylessly","jaggedly", 

"kindly", "kaleidoscopically",

"laggedly", "laggingly", "lamely", "lazily", "longingly", "lovingly", "lustfully", 
"loudly",

"madly", "magically", "majestically", "malevolently", "meanfully","meekly", 
"mercifully", "mercilessly", "merrily", "meticulously","mightily", "mildly", 
"mimically", "mischievously", "miserably", "mockingly", "monstrously", 
"mournfully", "musically", "mythically", "mystically", 

"naughtily", "neatly", "needlessly", "nicely", "noisily", "nonchalantly", 

"oafishly","obediently","obscurely", "oddly", "openly", 

"painfully", "passionately", "pathetically", "patiently", "peculiarly","pervertedly", 
"philantropically", "philosophically", "pitifully", "playfully", "poetically", 
"politely", "poorly", "powerfully", "promptly", "protectively", "proudly", 
"pricelessly", "privately","profoundly","proudly",

"questioningly","quickly", "quizzically", 

"rabidly", "radically","remorsefully", "repeatedly", "repulsively", "respectfully",
"restfully","restlessly", "reverently", "rhetorically", "rudely", "ruthlessly",

"sadly", "sarcastically", "satanically", "savagely", "sceptically", "scornfully", 
"selfishly", "selflessly", "sensually", "sensitively", "seriously", 
"sexily", "shamelessly", "sheepishly", "shrilly", "silently", "sinfully", "skillfully", 
"sleepily", "slightly", "slowly","spookily", "solemnly", "softly", "sourly", 
"speechlessly", "sternly","stealthily", "stonedly", "strangely", "stupidly", 
"subconsciously", "subtly", "suspiciously", "suggestively", "sweetly", 

"tamely","teasingly","tearlessly","technically", "terribly", "thankfully", 
"theoretically", "thoroughly", "thoughtfully", "thoughtlessly", 
"threateningly","tiredly", "toothlessly", "tragically", "triumphantly", 
"truthfully", "trustfully", "tunefully", 

"unanimously", "unwittingly", "uncomfortably", "uncontrollably", "uneasily",
"unkindly", "unwillingly", "utterly", 

"vastly", "vengefully", "vigorously", "viciously", "violently", "virtually",
"voluntarily", "vulnerably",

"warmly","wetly", "weakly", "weirdly", "wholeheartedly", "wickedly", "wildly",
"willingly", "wimpily", "wisely", "wondrously", "wrathfully", "wrongfully", "wryly", 

"xenophobically", 

"youthfully",

"zealously", "zen-likely", "zymotically", });

// Emotes

/* k:emote; 0:verb; 1:conjverb; 2:prep; 3:def_adverb; 4:def_bpart;
 * 5:def_target; 6:req_target; 7: bodyprep; 8:adverb_postition
 */
e_map=([
  "ack":"ack";"acks";"at";0;0;0;0;0;0,
  "agree":"agree";"agrees";"with";0;0;0;0;0;0,
  "ah":"go 'Ah'";"goes 'Ah'";"at";0;0;0;0;0;0,
  "apologize":"apologize";"apologizes";"to";0;0;0;0;0;0,
  "applaud":"applaud";"applauds";"at";0;0;0;0;0;0,
  "argh":"go 'Aarrgghh!'";"goes 'Aarrgghh!'";"at";0;0;0;0;0;0,
  "aww":"go 'Aww'";"goes 'Aww'";"at";0;0;0;0;0;0,
  "bark":"bark";"barks";"at";0;0;"like a dog";0;0;0,
  "beg":"beg";"begs";0;"shamelessly";0;0;0;0;0,
  "belch":"belch";"belches";0;"rudely";0;0;0;0;0,
  "blah":"go 'blah'";"goes 'blah'";"at";0;0;0;0;0;0,
  "bleed":"bleed";"bleeds";"on";0;0;0;0;0;0,
  "blink":"blink";"blinks";"at";0;0;0;0;0;0,
  "blush":"blush";"blushes";"at";"shyly";0;0;0;0;0,
  "beep":"beep";"beeps";0;"playfully";"nose";0;"on the";1;2,
  "boggle":"boggle";"boggles";"at";0;0;0;0;0;0,
  "bonk":"bonk";"bonks";0;"barbarically";"head";0;"on the";1;0,
  "boo":"boo";"boos";"at";"disappointedly";0;0;0;0;0,
  "bore":"bore";"bores";0;"unwittingly";0;0;0;1;0,
  "bored":"seem bored";"seems bored";"by";0;0;0;0;0;0,
  "bounce":"bounce";"bounces";"around";"joyfully";0;0;0;0;0,
  "bow":"bow";"bows";"to";"gracefully";0;0;0;0;1,
  "burp":"burp";"burps";"at";"rudely";0;0;0;0;0,
  "cackle":"cackle";"cackles";"at";"gleefully";0;0;0;0;0,
  "caress":"caress";"caresses";0;"fondly";0;0;0;0;0,
  "ccl":"couldn't care less";"couldn't care less";"about";0;0;0;0;0;0,
  "cheer":"cheer";"cheers";"at";"enthusiastically";0;0;0;0;0,
  "chuckle":"chuckle";"chuckles";"at";"good-heartedly";0;0;0;0;0,
  "clap":"clap";"claps";"at";"appreciatively";0;0;0;0;0,
  "click":"click your tongue";"clicks "+poss+" tongue";"at";"disapprovingly";0;0;0;0;0,
  "comfort":"comfort";"comforts";0;0;0;0;0;1;0, 
  "confuse":"confuse";"confuses";0;"stealthily";0;0;0;0;0,
  "confused":"seem confused";"seems confused";"by";0;0;0;0;0;0,
  "congratulate":"congratulate";"congratulates";0;"wholeheartedly";0;0;0;0;0,
  "cough":"cough";"coughs";"at";"noisily";0;0;0;0;0,
  "croak":"croak";"croaks";"at";0;0;0;0;0;0,
  "cry":"cry";"crys";"at";"inconsolably";0;0;0;0;0,
  "cuddle":"cuddle";"cuddles";0;"fondly";0;0;0;1;0,
  "curse":"curse";"curses";"at";"wrathfully";0;0;0;0;0,
  "curtsey":"curtsey";"curtseys";"to";"gracefully";0;0;0;0;0, 
  "dance":"dance";"dances";"with";"merrily";0;0;0;0;0,
  "die":"die";"dies";"on";"dramatically";0;0;0;0;0,
  "dis":"disrisp3kt";"disrisp3kts";0;"thoroughly";0;"everyone";0;0;0,
  "disagree":"disagree";"disagrees";"with";0;0;0;0;0;0,
  "dream":"dream";"dreams";"about";"longingly";0;0;0;1;0,
  "drool":"drool";"drools";"at";"uncontrollably";0;0;0;0;0,
  "eww":"go 'Eww!'";"goes 'Eww!'";"at";0;0;0;0;0;0,
  "eep":"eep";"eeps";"at";"fearfully";0;0;0;0;0,
  "evvk":"couldn't care less";"couldn't care less";"about";0;0;0;0;0;0,
  "faint":"faint";"faints";"before";"subtly";0;0;0;0;0,
  "fart":"fart";"farts";"at";"cheesily";0;0;0;0;0,
  "fear":"fear";"fears";0;0;0;0;0;1;0,
  "flee":"try to flee";"tries to flee";"from";0;0;0;0;0;1,
  "flex":"flex your muscles";"flexes "+poss+" muscles";"at";0;0;0;0;0;0,
  "flirt":"flirt";"flirts";"with";"openly";0;0;0;0;0,
  "fondle":"fondle";"fondles";0;"lustily";0;0;0;1;0,
  "french":"suck";"sucks";"on";"passionately";"tongue";0;0;1;0,
  "frown":"frown";"frowns";"at";"disapprovingly";0;0;0;0;0,
  "gasp":"gasp";"gasps";"at";"astonishedly";0;0;0;0;0,
  "giggle":"giggle";"giggles";"at";"merrily";0;0;0;0;0,
  "gigglesnort":"gigglesnort";"gigglesnorts";"at";"lamely";0;0;0;0;0,
  "glare":"glare";"glares";"at";"angrily";0;0;0;0;0,
  "gnn":"go 'Gnnn'";"goes 'Gnnn'";"at";0;0;0;0;0;0,
  "greet":"greet";"greets";0;0;0;"everyone";0;0;0,
  "grin":"grin";"grins";"at";"widely";0;0;0;0;1,
  "groan":"groan";"groans";"at";"loudly";0;0;0;0;0,
  "grope":"grope";"gropes";0;0;0;0;0;1;0,
  "growl":"growl";"growls";"at";0;0;"like a beast";0;0;0, 
  "grr":"go 'GRR'";"goes 'GRR'";"at";0;0;0;0;0;0,
  "grrmrr":"go 'GRRMRR'";"goes 'GRRMRR'";"at";0;0;0;0;0;0,
  "gurgle":"gurgle";"gurgles";"at";"toothlessly";0;0;0;0;1,
  "hail":"hail";"hails";0;0;0;0;0;1;0,
  "heh":"go 'Heh'";"goes 'Heh'";"at";0;0;0;0;0;0,
  "hiccup":"hiccup";"hiccups";"at";"uncontrollably";0;0;0;0;0,
  "hmm":"hmm";"hmms";"at";"thoughtfully";0;0;0;0;0,
  "hmpf":"hmpf";"hmpfs";"at";0;0;0;0;0;1,
  "hooray":"yell 'Hooray!'";"yells 'Hooray!'";"at";0;0;0;0;0;0,
  "hug":"hug";"hugs";0;"warmly";0;0;0;1;0,
  "huggle":"huggle";"huggles";0;"softly";0;0;0;1;0,
  "huh":"go 'Huh?'";"goes 'Huh?'";"at";0;0;0;0;0;0,
  "hum":"hum a little tune";"hums a little tune";"at";0;0;0;0;0;0,
  "huoh":"huoh";"huohs";"at";0;0;0;0;0;0,
  "hold":"hold";"holds";0;"fondly";0;0;0;1;0,
  "hop":"hop";"hops";"around";0;0;"around like a bunny";0;0;1,
  "jump":"jump";"jumps";"on";0;"frustratedly";"up and down";0;0;0,   
  "kick":"kick";"kicks";0;0;"knee";0;"in the";1;2,
  "kiss":"kiss";"kisses";0;"fondly";0;0;"on the";1;0,
  "laugh":"laugh";"laughs";"at";"heartily";0;0;0;0;0,   
  "lick":"lick";"licks";0;0;0;0;0;1;0,
  "laf":"laf";"lafs";"at";0;0;0;0;0;0,
  "lol":"laugh out loud";"laughs out loud";"at";0;0;0;0;0;0,
  "love":"love";"loves";0;"deeply";0;0;0;1;0,
  "lust":"are full of lust";"seems full of lust";"for";0;0;0;0;0;0,
  "mmm":"go 'mmm'";"goes 'mmmm'";"at";0;0;0;0;0;0,
  "meep":"meep";"meeps";"at";0;0;0;0;0;0,
  "moan":"moan";"moans";"at";0;0;0;0;0;1,
  "mourn":"mourn";"mourns";0;"deeply";0;0;0;0;0,  
  "moo":"you 'MOO' like a cow";"MOOs like a cow";"at";0;0;0;0;0;0,
  "moon":"pull down your pants and moon";
         "pulls down "+poss+" pants and moons";0;0;0;"everyone";0;0;0,
  "mosh":"mosh";"moshes";"at";"uncontrollably";0;0;0;0;0,
  "mrr":"go 'MRR'";"goes 'MRR'";"at";0;0;0;0;0;0,
  "mrrgrr":"go 'MRRGRR'";"goes 'MRRGRR'";"at";0;0;0;0;0;0,
  "muah":"MUAH";"MUAHs";"at";0;0;0;0;0;0,
  "neener":"go 'Neener-neener'";"goes 'Neener-neener'";"at";0;0;0;0;0;0,
  "nibble":"nibble";"nibbles";"on";0;"ear";0;0;1;0,
  "no":"say 'No'";"says 'No'";"at";"clearly";0;0;0;0;0,
  "noo":"wail 'Nooo-oo!'";"wails 'Nooo-oo!'";"at";0;0;0;0;0;0,
  "nod":"nod";"nods";"at";"solemnly";0;0;0;0;1,
  "nodnod":"nod twice in agreement";"nods twice in agreement";"at";0;0;0;0;0;0,
  "nog":"nog";"nogs";"at";"noggingly";0;0;0;0;1,
  "nognog":"nogs twice";"nogs twice";"at";"knowingly";0;0;0;0;0,
  "nogglepuuh":"noggle while going 'Puuh'";"noggles while going 'Puuh'";"at";0;0;0;0;0;0,
  "nuuh":"go 'nuuh'";"goes 'nuuh'";"at";0;0;0;0;0;0,
  "observe":"observe";"observes";0;"closely";0;0;0;0;0,
  "ooo":"go 'OK'";"goes 'OK'";"at";0;0;0;0;0;0,
  "ooo":"go 'Oooo'";"goes 'Oooo'";"at";0;0;0;0;0;0,
  "oops":"go 'Oops'";"goes 'Oops'";"at";0;0;0;0;0;0,
  "ouch":"go 'Ouch!'";"goes 'Ouch!'";"at";0;0;0;0;0;0,
  "pat":"pat";"pats";0;0;"head";0;"on the";1;2,
  "pet":"pet";"pets";0;0;0;0;0;1;0,
  "piss":"piss";"pisses";"on";0;0;"in the corner";0;0;0,
  "pok":"pok";"poks";0;0;0;0;0;0;0,   
  "pokpok":"pok";"pok";"at";
           "from what seems like from every direction at once";0;0;0;0;0,   
  "poke":"poke";"pokes";0;0;"ribs";0;"in the";1;2,
  "ponder":"ponder";"ponders";"about";0;0;"about the transience of life";0;0;1,
  "pout":"pout";"pouts";"at";0;0;0;0;0;0,
  "point":"point";"points";"at";0;0;0;0;1;0,
  "puke":"puke";"pukes";"on";0;0;"on the floor";0;0;0,
  "pull":"pull";"pulls";"on";0;"finger";0;0;1;0,
  "punch":"punch";"punches";0;0;"nose";0;"in the";1;0,
  "puppy":"make puppy dog eyes";"makes puppy dog eyes";"at";0;0;0;0;1;0,
  "purr":"purr";"purrs";"at";"softly";0;0;0;0;0,
  "puuh":"puuh";"puuhs";"at";0;0;0;0;0;0,
  "rofl":"roll on the floor laughing";"rolls on the floor laughing";"at";0;0;0;0;0;0,
  "ruffle":"ruffle";"ruffles";0;"playfully";"hair";0;0;1;0,
  "rokpok":"rokpok";"rokspoks";0;0;0;0;0;0;0,
  "sad":"seem sad";"seems sad";"at";0;0;0;0;0;0,
  "scare":"try to scare";"tries to scare";0;"spookily";0;0;0;1;0,
  "scratch":"scratch";"scratches";0;0;"head";0;0;0;0,
  "scream":"scream";"screams";"at";"loudly";0;0;0;0;0,
  "shake":"shake your head";"shakes "+poss+" head";"at";0;0;0;0;0;0,
  "shiver":"shiver";"shivers";"at";"fearfully";0;0;0;0;0,
  "shrug":"shrug";"shrugs";"at";"helplessly";0;0;0;0;0,
  "sigh":"sigh";"sighs";"at";"deeply";0;0;0;0;0,
  "sing":"sing";"sings";"at";"beautifully";0;0;0;0;0,
  "slap":"slap";"slaps";0;0;"cheek";0;"on the";1;2,
  "slobber":"slobber";"slobbers";"on";"repulsively";0;0;0;0;0,
  "smirk":"smirk";"smirks";"at";"wryly";0;0;0;0;0,
  "smile":"smile";"smiles";"at";"happily";0;0;0;0;1,
  "snap":"snap your fingers";"snaps "+poss+" fingers";"at";0;0;0;0;0;0,
  "sneeze":"sneeze";"sneezes";"at";0;0;0;0;0;0,
  "snicker":"snicker";"snickers";"at";0;0;0;0;0;0,
  "sniff":"sniff";"sniffs";"at";"sadly";0;0;0;0;0,
  "sniffle":"sniffle";"sniffles";"at";"silently";0;0;0;0;0,
  "snore":"snore";"snores";"at";0;0;0;0;0;0,
  "snuggle":"snuggle";"snuggles";"up to";0;0;0;0;1;0,
  "sob":"sob";"sobs";"on";"unconsolably";0;0;0;0;0,
  "sorry":"go 'Sorry...'";"goes 'Sorry...'";"at";0;0;0;0;0;0,
  "spank":"spank";"spanks";0;"forcefully";0;0;0;1;0,  
  "spit":"spit";"spits";"on";"defiantly";0;0;0;0;0,
  "squeeze":"squeeze";"squeezes";0;0;0;0;0;0;0,
  "stare":"stare";"stares";"at";0;0;"into the horizon";0;0;0,
  "stomp":"stomp";"stomps";0;0;0;"to the beat";0;0;0,
  "strip":"start stripping";"starts stripping";"for";"erotically";0;0;0;0;0,
  "suck":"suck";"sucks";"on";0;"finger";0;0;1;0,
  "sulk":"sulk";"sulks";"at";0;0;0;0;0;0,
  "tap":"tap your foot";"taps "+poss+" foot";"at";"impatiently";0;0;0;0;0,
  "taunt":"taunt";"taunts";0;0;0;0;0;1;0,
  "tease":"tease";"teases";0;"playfully";0;0;0;1;0,
  "thank":"thank";"thanks";0;0;"gratefully";"everyone";0;0;0,
  "think":"think";"thinks";"about";0;0;"about some pressing matter";0;0;0,
  "tickle":"tickle";"tickles";0;"playfully";0;0;0;1;0,
  "thumb":"give a thumbs up";"gives a thumbs up";"to";0;0;0;0;0;0,
  "touch":"touch";"touches";0;"arousingly";0;0;0;1;0,
  "tremble":"tremble";"trembles";"at";"fearfully";0;"with fear";0;0;0,
  "tsk":"go 'tsk'";"goes 'tsk'";"at";0;0;0;0;0;0,
  "twiddle":"twiddle your thumbs";"twiddles "+poss+" thumbs";"at";0;0;0;0;0;0,
  "uuh":"go 'Uuuhh'";"goes 'Uuuhh'";"at";0;0;0;0;0;0,
  "wait":"wait";"waits";"for";0;0;0;0;0;0,
  "wake":"try to wake";"tries to wake";0;0;0;0;0;0;0,
  "wave":"wave";"waves";"at";"happily";0;0;0;0;0,
  "whine":"whine";"whines";"at";0;0;"about life in general";0;0;0,
  "whistle":"whistle";"whistles";"at";"appreciatively";0;0;0;0;1,
  "wiggle":"wiggle your butt";"wiggles "+poss+" butt";"at";0;0;0;0;0;0,
  "wonder":"wonder";"wonders";"about";0;0;"about this and that";0;0;0,
  "worship":"worship";"worships";0;0;0;"Nalle reverently";0;0;0,
  "wink":"wink";"winks";"at";"suggestively";0;0;0;0;0,
  "wow":"go 'Wow'";"goes 'Wow'";"at";0;0;0;0;0;0,  
  "yawn":"yawn";"yawns";"at";"tiredly";0;0;0;0;0,
  "yes":"say 'Yes'";"says 'Yes'";"at";"plainly";0;0;0;0;0,
  "yodel":"yodel";"yodels";"at";"tunefully";0;0;0;0;0
 ]);

   e_array=m_indices(e_map);
} 

